version: "2.4"
services:
  portrait:
    image: ghcr.io/iosifache/oss_fortress_portrait:main
    container_name: portrait
    ports:
      - "8000:8080"
    environment:
      - PORTRAIT_RECOVERY_PASSPHRASE=secret
  code:
    image: codercom/code-server:latest
    container_name: code
    volumes:
      - "$PWD/analysis:/home/coder/analysis"
    ports:
      - "8081:8080"
    environment:
      - DOCKER_USER=$USER
    depends_on:
      - portrait
  owasp_threat_dragon:
    image: owasp/threat-dragon:latest
    container_name: dragon
    volumes:
      - "$PWD/analysis:/analysis"
    ports:
      - "8002:8080"
    environment:
      - GITHUB_CLIENT_ID=0a03b2a7f594695eb9e3
      - GITHUB_CLIENT_SECRET=5c16f90f924ce06debb2406aadaea6ecdda3ee82
      - GITHUB_SCOPE=oss_fortress
      - GITHUB_ENTERPRISE_HOSTNAME=canonical
      - GITHUB_ENTERPRISE_PORT=1337
      - GITHUB_ENTERPRISE_PROTOCOL=https
      - NODE_ENV=production
      - SERVER_API_PROTOCOL=http
      - ENCRYPTION_KEYS="[{\"isPrimary\": true, \"id\": 0, \"value\": \"11223344556677889900aabbccddeeff\"}]"
      - ENCRYPTION_JWT_SIGNING_KEY=asdfasdfasdf
      - ENCRYPTION_JWT_REFRESH_SIGNING_KEY=fljasdlfkjadf
    depends_on:
      - portrait
