name: Tests the Docker Compose infrastructure
on:
  push:
    branches:
      - main
    paths:
      - sandcastle
      - tooling
      - .github/workflows/ghcr-publish.yml
      - .github/workflows/analysis-infra-smoke-test.yml
      - docker-compose.yaml
  schedule:
    - cron: "0 0 * * *"
jobs:
  smoke-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: sandcastle
          - name: dragon
          - name: coder
          - name: static-analysers
          - name: aflplusplus
          - name: klee
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Test Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yaml"
          services: |
            ${{ matrix.name }}
