name: Tests the Docker Compose 
on:
  push:
    branches:
      - main
    paths:
      - sandcastle
      - tooling
      - .github/workflows/ghcr-publish.yml
      - .github/workflows/analysis-infra-smoke-test.yml
      - docker-compose.yaml
  schedule:
    - cron: "0 0 * * *"
jobs:
  smoke-tes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Test Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yaml"
          compose-flags: "--profile all"
      - name: Execute tests inside the sandcastle container
        run: docker-compose exec sandcastle "echo 'Hi'"
      - name: Execute tests inside the dragon container
        run: docker-compose exec dragon "echo 'Hi'"
      - name: Execute tests inside the coder container
        run: docker-compose exec coder "echo 'Hi'"
      - name: Execute tests inside the static-analysers container
        run: docker-compose exec static-analysers "echo 'Hi'"
      - name: Execute tests inside the aflplusplus container
        run: docker-compose exec aflplusplus "echo 'Hi'"
      - name: Execute tests inside the klee container
        run: docker-compose exec klee "echo 'Hi'"
