# Relevant docs: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

name: Create and publish Docker images to GHCR
on:
  push:
    branches:
      - main
    paths:
      - sandcastle
      - tooling
      - .github/workflows/ghcr-publish.yml
env:
  REGISTRY: ghcr.io
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - id: sandcastle
            context: sandcastle
          - id: coder
            context: tooling/coder
          - id: static-analysis
            context: tooling/static-analysers
          - id: afplusplus
            context: tooling/aflplusplus
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract the tag and labels for the Docker image
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/oss-fortress-${{ matrix.id }}
      - name: Build and push the Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
